### ISSUE TITLE
Carrier Offset Correction

### ISSUE THREAD

**Issue by tfcollins** [tvelliott/charon#1]
First of all, great project!  Love to see people doing cool things with Pluto.

With regards to some of the carrier offset tuning.  It might be useful to just use the CFO estimate (nco_crcf_get_frequency) of the OFDM preamble to tune the XO correction in Pluto.  Even with bad packets, this might get you closer.

There is also a little app we use to calibrate the XO with a tone at a known frequency (https://github.com/analogdevicesinc/plutosdr_scripts/blob/master/cal_ad9361.c).  You can just run this once so you don't have to guess when setting the XO correction value.  You can just use the BIST tones on one Pluto to calibrate against (similar to https://github.com/analogdevicesinc/rfsom-box-gui/blob/master/bin/send_tone.sh).

**Comment by tvelliott** [comment]
Travis,  thanks for the comments.  The ofdm receiver implementation does already use an NCO to do course and fine frequency correction for each received frame  (as well as phase, magnitude correction).  The reason the initial frequency offset has to be close is because the channel is narrow (~140KHz) with 64 sub-carriers,  so something around 2 KHz / carrier...  

I have not tried the ad9361 cal code yet.  That sounds like a great way to get them all relatively close to each other.  I will get that figured out and update the main page with a reference.  Thank you.

**Comment by rgetz** [comment]
@tvelliot - I think @tfcollins was suggesting to use the frequency offset calculation to fix the XO correction value. This way - things would track over temperature changes better. 

- Robin

**Comment by tvelliott** [comment]
@tfcollins @rgetz 
Travis,  Robin.   I apologize.  I did misunderstand the suggestion to use (nco_crcf_get_frequency) for XO correction.  I've added these suggestions and links to the readme.md file and will try them out when I get back to working on this project.  Thank you again for taking the time to comment and for the help.  I have a lot of respect for the work you guys do.  I saw a reference to your new book today.  Congratulations on the publication!  It looks very good.  Looking forward to learning from it.
